CREATE TABLE "difficulties" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL UNIQUE
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL UNIQUE
);

CREATE TABLE "questions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "difficulty_id" int NOT NULL REFERENCES "difficulties" ("id"),
  "cat_id" int NOT NULL REFERENCES "categories" ("id"),
  "number" int NOT NULL,
  "text" varchar(1000) NOT NULL
);

CREATE TABLE "user_answers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL REFERENCES "users" ("id"),
  "question_id" int NOT NULL REFERENCES "questions" ("id"),
  "accuracy" int NOT NULL CHECK (accuracy >= 0 AND accuracy <= 100),
  "point" int NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "rooms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL REFERENCES "users" ("id"),
  "name" varchar(100) NOT NULL UNIQUE,
  "description" varchar(500),
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "started_at" timestamp,
  "ended_at" timestamp
);

-- Create indexes for better query performance
CREATE INDEX idx_questions_difficulty ON questions(difficulty_id);
CREATE INDEX idx_questions_category ON questions(cat_id);
CREATE INDEX idx_user_answers_user ON user_answers(user_id);
CREATE INDEX idx_user_answers_question ON user_answers(question_id);
CREATE INDEX idx_rooms_user ON rooms(user_id);
